### ISSUE TITLE
Issue with latest python repl

### ISSUE THREAD

**Issue by zegervdv** [hkupty/iron.nvim#6]
When running `UpdateRemotePlugins` I get the following error: 

~~~
Encountered SyntaxError loading plugin at /home/zegervdv/.config/nvim/plugged/iron.nvim/rplugin/python3/iron: invalid syntax (__init__.py, line 21)
Traceback (most recent call last):
  File "/home/zegervdv/.local/lib/python3.5/site-packages/neovim/plugin/host.py", line 132, in _load
    module = imp.load_module(name, file, pathname, descr)
  File "/usr/lib/python3.5/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.5/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/home/zegervdv/.config/nvim/plugged/iron.nvim/rplugin/python3/iron/repls/__init__.py", line 21
    python.ptipython,
         ^
SyntaxError: invalid syntax
~~~

Reverting to 2da42c8 solves the issue.

**Comment by hkupty** [comment]
Thanks for reporting and fixing!
